#!/usr/bin/env python3
"""
TradingBot Pro — Multi-exchange, multi-strategy autonomous trading bot
Author: Generated by Claude
"""

import asyncio
import signal
import sys
from core.bot_engine import BotEngine
from core.logger import setup_logger
from config.settings import load_config

logger = setup_logger("main")


async def main():
    config = load_config()
    bot = BotEngine(config)

    # Graceful shutdown on SIGINT / SIGTERM
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(sig, lambda: asyncio.create_task(bot.shutdown()))

    logger.info("🚀 TradingBot Pro starting...")
    await bot.run()


if __name__ == "__main__":
    asyncio.run(main())
